version: "3.8"
configs:
  app_config:
    file: ./configs/config.yaml
services:
  judge:
    build:
      context: .
      dockerfile: .docker/local-build.Dockerfile
    entrypoint: /app/scripts/judge.docker-entrypoint.sh
    pull_policy: build
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_started
    configs:
      - source: app_config
        target: /app/configs/config.yaml
    environment:
      - DATABASE__HOST=postgres
      - DATABASE__PORT=5432
      - DATABASE__USERNAME=gojudge
      - DATABASE__PASSWORD=complex-password
      - DATABASE__NAME=gojudge
    restart: unless-stopped
    networks:
      - runner-network
      - db-network
  runner:
    build:
      context: .
      dockerfile: .docker/local-build.Dockerfile
    entrypoint: /app/scripts/runner.docker-entrypoint.sh
    pull_policy: build
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    configs:
      - source: app_config
        target: /app/configs/config.yaml
    deploy:
      replicas: 3
    privileged: true
    healthcheck:
      test: ["CMD", "grpc_health_probe", "-addr=:8888"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    depends_on:
      image-puller:
        condition: service_completed_successfully
      util-volume-creator:
        condition: service_completed_successfully
    networks:
      - runner-network
  image-puller:
    image: docker:cli
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      sh -c "echo 'Pulling required Docker images...' &&



        docker pull golang:1.23 &&
        docker pull ubuntu:22.04 &&
        echo 'All required images pulled successfully!'
      "

    restart: "no"
  util-volume-creator:
    image: golang:1.23
    volumes:
      - go-runner-utils:/app
      - ./utils:/utils
    command: go build -o /app/spy /utils/spy.go
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=gojudge
      - POSTGRES_PASSWORD=complex-password
      - POSTGRES_DB=gojudge
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - db-network
networks:
  db-network:
    driver: bridge
  runner-network:
    driver: bridge
volumes:
  postgres-data:
    driver: local
  go-runner-utils:
