// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: problems.sql

package storage

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAllProblemsSorted = `-- name: GetAllProblemsSorted :many
SELECT id, title, description, sample_input, sample_output, time_limit_ms, memory_limit_kb, created_at, created_by
FROM problems
ORDER BY created_at DESC
`

func (q *Queries) GetAllProblemsSorted(ctx context.Context, db DBTX) ([]Problem, error) {
	rows, err := db.Query(ctx, getAllProblemsSorted)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Problem
	for rows.Next() {
		var i Problem
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.SampleInput,
			&i.SampleOutput,
			&i.TimeLimitMs,
			&i.MemoryLimitKb,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProblemByID = `-- name: GetProblemByID :one
SELECT id, title, description, sample_input, sample_output, time_limit_ms, memory_limit_kb, created_at, created_by
FROM problems
WHERE id = $1
`

func (q *Queries) GetProblemByID(ctx context.Context, db DBTX, id int32) (Problem, error) {
	row := db.QueryRow(ctx, getProblemByID, id)
	var i Problem
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.SampleInput,
		&i.SampleOutput,
		&i.TimeLimitMs,
		&i.MemoryLimitKb,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const insertProblem = `-- name: InsertProblem :one
INSERT INTO problems (
    title,
    description,
    sample_input,
    sample_output,
    time_limit_ms,
    memory_limit_kb,
    created_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, title, description, sample_input, sample_output, time_limit_ms, memory_limit_kb, created_at, created_by
`

type InsertProblemParams struct {
	Title         string      `db:"title" json:"title"`
	Description   string      `db:"description" json:"description"`
	SampleInput   string      `db:"sample_input" json:"sample_input"`
	SampleOutput  string      `db:"sample_output" json:"sample_output"`
	TimeLimitMs   int64       `db:"time_limit_ms" json:"time_limit_ms"`
	MemoryLimitKb int64       `db:"memory_limit_kb" json:"memory_limit_kb"`
	CreatedBy     pgtype.UUID `db:"created_by" json:"created_by"`
}

func (q *Queries) InsertProblem(ctx context.Context, db DBTX, arg InsertProblemParams) (Problem, error) {
	row := db.QueryRow(ctx, insertProblem,
		arg.Title,
		arg.Description,
		arg.SampleInput,
		arg.SampleOutput,
		arg.TimeLimitMs,
		arg.MemoryLimitKb,
		arg.CreatedBy,
	)
	var i Problem
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.SampleInput,
		&i.SampleOutput,
		&i.TimeLimitMs,
		&i.MemoryLimitKb,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}
