// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package storage

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateUser(ctx context.Context, db DBTX, username string, passwordHash string) (User, error)
	GetUser(ctx context.Context, db DBTX, id pgtype.UUID) (User, error)
	GetUserByUsername(ctx context.Context, db DBTX, username string) (User, error)
}

var _ Querier = (*Queries)(nil)
