// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: submissions.sql

package storage

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSubmission = `-- name: CreateSubmission :one
INSERT INTO submissions (problem_id, user_id, solution_code)
VALUES ($1, $2, $3)
RETURNING id, problem_id, user_id, solution_code, status, created_at, last_modified, message, retries
`

type CreateSubmissionParams struct {
	ProblemID    int32       `db:"problem_id" json:"problem_id"`
	UserID       pgtype.UUID `db:"user_id" json:"user_id"`
	SolutionCode string      `db:"solution_code" json:"solution_code"`
}

func (q *Queries) CreateSubmission(ctx context.Context, db DBTX, arg CreateSubmissionParams) (Submission, error) {
	row := db.QueryRow(ctx, createSubmission, arg.ProblemID, arg.UserID, arg.SolutionCode)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.UserID,
		&i.SolutionCode,
		&i.Status,
		&i.CreatedAt,
		&i.LastModified,
		&i.Message,
		&i.Retries,
	)
	return i, err
}

const retrySubmissionDueToInternalError = `-- name: RetrySubmissionDueToInternalError :one
UPDATE submissions
SET retries = retires + 1
WHERE id = $1
RETURNING id, problem_id, user_id, solution_code, status, created_at, last_modified, message, retries
`

func (q *Queries) RetrySubmissionDueToInternalError(ctx context.Context, db DBTX, id pgtype.UUID) (Submission, error) {
	row := db.QueryRow(ctx, retrySubmissionDueToInternalError, id)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.UserID,
		&i.SolutionCode,
		&i.Status,
		&i.CreatedAt,
		&i.LastModified,
		&i.Message,
		&i.Retries,
	)
	return i, err
}

const updateSubmissionStatus = `-- name: UpdateSubmissionStatus :one
UPDATE submissions
SET status = $2, message = $3
WHERE id = $1
RETURNING id, problem_id, user_id, solution_code, status, created_at, last_modified, message, retries
`

type UpdateSubmissionStatusParams struct {
	ID      pgtype.UUID      `db:"id" json:"id"`
	Status  SubmissionStatus `db:"status" json:"status"`
	Message pgtype.Text      `db:"message" json:"message"`
}

func (q *Queries) UpdateSubmissionStatus(ctx context.Context, db DBTX, arg UpdateSubmissionStatusParams) (Submission, error) {
	row := db.QueryRow(ctx, updateSubmissionStatus, arg.ID, arg.Status, arg.Message)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.UserID,
		&i.SolutionCode,
		&i.Status,
		&i.CreatedAt,
		&i.LastModified,
		&i.Message,
		&i.Retries,
	)
	return i, err
}
