name: Build

on:
  push:
    branches:
      - '*'
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.23.3'
          cache: true
      
      - name: Build
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: build --clean --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: download-manager-binaries
          path: dist/*/download-manager*
          retention-days: 5
