name: Go Tests
on:
  push:
    branches:
      - "*"
  pull_request:
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ">=1.23.3"
          cache: true
      - name: Install dependencies
        run: go mod download
      - name: Run tests
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
